language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t vilaverde/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true vilaverde/docker-react-travis yarn run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-992544047821"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
